---

- name: AWX | Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: AWX | Install prerequisites
  package:
    name: "{{ awx_prerequisites_packages }}"
    state: present

- name: AWX | Unarchive sources
  unarchive:
    src: "{{ awx_source_repository_url }}"
    dest: "{{ awx_source_dir }}"
    owner: root
    group: root
    remote_src: yes
    creates: "{{ awx_source_dir }}/awx-{{ awx_version }}"

- name: AWX | Manage directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{ awx_postgres_data_dir }}"

- name: AWX | Run the AWX installation playbook
  command: "ansible-playbook -i inventory install.yml -e postgres_data_dir={{ awx_postgres_data_dir }}"
  args:
    chdir: "{{ awx_source_dir }}/awx-{{ awx_version }}/installer"
